apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: bachelorarbeit
    name: mongodb
spec:
  ports:
    - port: 3306
  selector:
    app: bachelorarbeit
    name: mongodb
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongodb
  labels:
    name: mongodb
    app: bachelorarbeit
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: bachelorarbeit
        name: mongodb
    spec:
      containers:
      - image: mongo
        name: mongodb
        ports:
        - name: mongo
          containerPort: 27017
        volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /data/db
      volumes:
      - name: mongo-persistent-storage
        gcePersistentDisk:
          pdName: mongo-disk
          fsType: ext4
