apiVersion: v1
kind: Service
metadata:
  name: {{ mongodbServiceName }}
  labels:
    name: {{ mongodbServiceName }}
    app: bachelorarbeit
spec:
  ports:
    - port: 27017
      targetPort: mongodb-port
  selector:
    name: mongodb
    app: bachelorarbeit
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongodb
  labels:
    name: mongodb
    app: bachelorarbeit
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: bachelorarbeit
        name: mongodb
    spec:
      containers:
      - image: mongo
        name: mongodb
        ports:
        - name: mongodb-port
          containerPort: 27017
        volumeMounts:
        - name: mongodb-persistent-storage
          mountPath: /data/db
      volumes:
      - name: mongodb-persistent-storage
        hostPath:
          path: /data/db
