apiVersion: v1
kind: Service
metadata:
  name: users-service
  labels:
    app: bachelorarbeit
    name: users-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: u-service-port
  selector:
    app: bachelorarbeit
    name: users-service
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: users-service
  labels:
    name: users-service
    app: bachelorarbeit
spec:
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: bachelorarbeit
        name: users-service
    spec:
      imagePullSecrets:
        - name: eu-west-1-ecr-registry
      containers:
      - image: {{ usersServiceImage }}:{{ usersServiceTag }}
        imagePullPolicy: Always
        name: users-service
        ports:
        - name: u-service-port
          containerPort: 80
        env:
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: userpassword
        - name: MYSQL_USER
          value: {{ usersServiceDbUsername }}
        - name: MYSQL_DATABASE
          value: {{ usersServiceDbName }}
        - name: MYSQL_HOST
          value: {{ mysqlServiceName }}
        - name: SECRET_KEY
          value: {{ usersServiceSecretKey }}
