apiVersion: v1
kind: ConfigMap
metadata:
  name: service-endpoints
  labels:
    app: bachelorarbeit
data:
  endpoints.json: |-
    {
      "usersServiceUrl": "{{ userServiceEndpoint }}",
      "productsServiceUrl": "{{ productsServiceEndpoint }}"
    }
