apiVersion: v1
kind: Service
metadata:
  name: web-service
  labels:
    app: bachelorarbeit
    name: web-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: w-service-port
  selector:
    app: bachelorarbeit
    name: web-service
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web-service
  labels:
    name: web-service
    app: bachelorarbeit
spec:
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: bachelorarbeit
        name: web-service
    spec:
      imagePullSecrets:
        - name: eu-west-1-ecr-registry
      containers:
        - image: {{ webServiceImage }}:{{ webServiceTag }}
          name: web-service
          env:
            - name: SERVICES_CONFIGURATION_FILE
              value: /etc/web-service/endpoints.json
          volumeMounts:
            - name: config-volume
              mountPath: /etc/web-service
            - name: static-html
              mountPath: /opt/app/dist
        - image: nginx:stable-alpine
          name: nginx
          ports:
            - name: w-service-port
              containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 20
            timeoutSeconds: 5
          volumeMounts:
            - name: static-html
              mountPath: /usr/share/nginx/html
      volumes:
        - name: static-html
          emptyDir: {}
        - name: config-volume
          configMap:
            name: service-endpoints
            items:
            - key: endpoints.json
              path: endpoints.json
